// src/app/components/header/header.component.ts
import {
  Component,
  OnInit,
  OnDestroy,
  ChangeDetectionStrategy,
} from '@angular/core';
import { Router, NavigationEnd } from '@angular/router';
import { filter } from 'rxjs';
import { LogoComponent } from '../logo/logo.component';
import { NAV_ITEMS } from '../../data/nav.data';
import {
  isNavDropdown,
  NavDropdownItem,
  NavItem,
  NavLink,
} from '../../models/nav.model';
import { DESKTOP_MQ } from '../../utils/mega-menu.utils';

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [LogoComponent],
  changeDetection: ChangeDetectionStrategy.Eager,
  templateUrl: './header.component.html',
})
export class HeaderComponent implements OnInit, OnDestroy {
  readonly navItems = NAV_ITEMS;

  mobileOpen = false;
  activePath = '/';
  activeHash = '';
  openDropdown: string | null = null;
  isDesktopNav = true;

  private mediaQuery = window.matchMedia(DESKTOP_MQ);
  private onHashChange = () => this.syncNavState();
  private onMediaChange = (e: MediaQueryListEvent) => {
    this.isDesktopNav = e.matches;
    if (e.matches) this.openDropdown = null;
  };
  private onKeyDown = (e: KeyboardEvent) => {
    if (e.key === 'Escape') this.closeDropdown();
  };
  private readonly navSub;

  constructor(private readonly router: Router) {
    this.navSub = this.router.events
      .pipe(filter((event) => event instanceof NavigationEnd))
      .subscribe(() => this.syncNavState());
  }

  ngOnInit(): void {
    this.syncNavState();
    this.isDesktopNav = this.mediaQuery.matches;
    window.addEventListener('hashchange', this.onHashChange);
    this.mediaQuery.addEventListener('change', this.onMediaChange);
    document.addEventListener('keydown', this.onKeyDown);
  }

  ngOnDestroy(): void {
    this.navSub.unsubscribe();
    window.removeEventListener('hashchange', this.onHashChange);
    this.mediaQuery.removeEventListener('change', this.onMediaChange);
    document.removeEventListener('keydown', this.onKeyDown);
  }

  isDropdown(item: NavItem): item is NavDropdownItem {
    return isNavDropdown(item);
  }

  asColumns(children: NavLink[] | NavLink[][]): NavLink[][] {
    return children as NavLink[][];
  }

  asLinks(children: NavLink[] | NavLink[][]): NavLink[] {
    return children as NavLink[];
  }

  flattenChildren(children: NavLink[] | NavLink[][]): NavLink[] {
    if (Array.isArray(children[0])) {
      return (children as NavLink[][]).flat();
    }
    return children as NavLink[];
  }

  isActive(href: string): boolean {
    if (href === '/contact') return this.activePath === '/contact';
    if (href === '/') return this.activePath === '/' && !this.activeHash;
    if (href.startsWith('/#')) return this.activePath === '/' && this.activeHash === href.slice(1);
    return false;
  }

  childIsActive(item: NavDropdownItem): boolean {
    const siblings = this.flattenChildren(item.children);
    return siblings.some((c) => this.isMegaLinkActive(c, siblings));
  }

  isMegaLinkActive(child: NavLink, siblings: NavLink[]): boolean {
    if (!this.isActive(child.href)) return false;
    const duplicates = siblings.filter((item) => item.href === child.href);
    return duplicates.length === 1;
  }

  onDropdownMouseDown(event: MouseEvent): void {
    if (this.isDesktopNav) event.preventDefault();
  }

  onDropdownEnter(label: string): void {
    if (this.isDesktopNav) return;
    this.openDropdown = label;
  }

  onDropdownLeave(): void {
    if (this.isDesktopNav) return;
    this.openDropdown = null;
  }

  toggleMobileDropdown(label: string): void {
    this.openDropdown = this.openDropdown === label ? null : label;
  }

  closeMobile(): void {
    this.mobileOpen = false;
    this.closeDropdown();
  }

  toggleMobileMenu(): void {
    this.mobileOpen = !this.mobileOpen;
  }

  isDropdownOpen(label: string): boolean {
    return !this.isDesktopNav && this.openDropdown === label;
  }

  private syncNavState(): void {
    const [path, hash = ''] = this.router.url.split('#');
    this.activePath = path || '/';
    this.activeHash = hash ? `#${hash}` : window.location.hash;
  }

  private closeDropdown(): void {
    this.openDropdown = null;
  }
}

<header class="site-header" [class.open]="mobileOpen" id="top">
  <div class="container header-inner">
    <a href="/" class="brand" aria-label="Jama Go Security home" (click)="closeMobile()">
      <app-logo variant="header" />
    </a>

    <nav class="main-nav" aria-label="Main navigation">
      @for (item of navItems; track item.label) {
        @if (isDropdown(item)) {
          <div
            class="nav-dropdown"
            [class]="'nav-dropdown nav-dropdown--' + item.menu"
            [class.open]="isDropdownOpen(item.label)"
            [class.active]="childIsActive(item)"
            (mouseenter)="onDropdownEnter(item.label)"
            (mouseleave)="onDropdownLeave()"
          >
            <button
              type="button"
              class="nav-link nav-link--dropdown"
              [attr.aria-expanded]="isDropdownOpen(item.label)"
              aria-haspopup="true"
              (mousedown)="onDropdownMouseDown($event)"
              (click)="!isDesktopNav && toggleMobileDropdown(item.label)"
            >
              {{ item.label }}
              <span class="nav-caret" aria-hidden="true"></span>
            </button>

            <div class="nav-mega">
              @if (item.menu === 'columns') {
                <div class="nav-mega-grid nav-mega-grid--2">
                  @for (column of asColumns(item.children); track column[0].label) {
                    <div class="nav-mega-col">
                      @for (child of column; track child.label) {
                        <a
                          [href]="child.href"
                          class="nav-mega-link"
                          [class.active]="isMegaLinkActive(child, column)"
                          (click)="closeMobile()"
                        >
                          {{ child.label }}
                        </a>
                      }
                    </div>
                  }
                </div>
              } @else if (item.menu === 'grid') {
                <div class="nav-mega-grid nav-mega-grid--3">
                  @for (child of asLinks(item.children); track child.label) {
                    <a
                      [href]="child.href"
                      class="nav-mega-link"
                      [class.active]="isMegaLinkActive(child, asLinks(item.children))"
                      (click)="closeMobile()"
                    >
                      {{ child.label }}
                    </a>
                  }
                </div>
              } @else {
                <div class="nav-mega-stack">
                  @for (child of asLinks(item.children); track child.label) {
                    <a
                      [href]="child.href"
                      class="nav-mega-link"
                      [class.active]="isMegaLinkActive(child, asLinks(item.children))"
                      (click)="closeMobile()"
                    >
                      {{ child.label }}
                    </a>
                  }
                </div>
              }
            </div>
          </div>
        } @else {
          <a
            [href]="item.href"
            class="nav-link"
            [class.active]="isActive(item.href)"
            (click)="closeMobile()"
          >
            {{ item.label }}
          </a>
        }
      }
    </nav>

    <a href="/contact" class="btn btn-primary btn-sm nav-cta" (click)="closeMobile()">
      Get a Quote
    </a>

    <button
      class="nav-toggle"
      aria-label="Toggle menu"
      [attr.aria-expanded]="mobileOpen"
      (click)="toggleMobileMenu()"
    >
      <span></span>
      <span></span>
      <span></span>
    </button>
  </div>
</header>

// src/components/Header.jsx
import { useEffect, useState } from "react";
import useMegaMenu from "../hooks/useMegaMenu.js";
import Logo from "./Logo.jsx";

const NAV_ITEMS = [
  { href: "#top", label: "Home" },
  {
    label: "About",
    children: [
      { href: "#why", label: "Why Us" },
      { href: "#contact", label: "About Us" },
      { href: "#stats", label: "Our Results" },
    ],
  },
  {
    label: "Services",
    dropdownClass: "nav-dropdown--services",
    children: [
      { href: "#services", label: "All Services" },
      { href: "#services", label: "Manned Guarding" },
      { href: "#services", label: "Mobile Patrols" },
      { href: "#services", label: "Event Security" },
      { href: "#services", label: "CCTV Monitoring" },
      { href: "#services", label: "Alarm Response" },
    ],
  },
  {
    label: "Solutions",
    children: [
      { href: "#services", label: "Commercial" },
      { href: "#services", label: "Residential" },
      { href: "#services", label: "Industrial" },
    ],
  },
  { href: "#contact", label: "Contact" },
];

function isActive(href, activeHash) {
  if (!href) return false;
  if (href === "#top") return activeHash === "#top" || activeHash === "";
  return activeHash === href;
}

function childIsActive(children, activeHash) {
  return children?.some((c) => isActive(c.href, activeHash));
}

export default function Header() {
  const [open, setOpen] = useState(false);
  const [activeHash, setActiveHash] = useState("#top");
  const {
    openDropdown,
    setOpenDropdown,
    isDesktopNav,
    closeDropdown,
    getDropdownHandlers,
  } = useMegaMenu();

  useEffect(() => {
    const syncHash = () => setActiveHash(window.location.hash || "#top");
    syncHash();
    window.addEventListener("hashchange", syncHash);
    return () => window.removeEventListener("hashchange", syncHash);
  }, []);

  const closeMobile = () => {
    setOpen(false);
    closeDropdown();
  };

  const toggleMobileDropdown = (label) => {
    setOpenDropdown((prev) => (prev === label ? null : label));
  };

  return (
    <header className={`site-header${open ? " open" : ""}`} id="top">
      <div className="container header-inner">
        <a href="#top" className="brand" aria-label="Jama Go Security home">
          <Logo variant="header" />
        </a>

        <nav className="main-nav" aria-label="Main navigation">
          {NAV_ITEMS.map((item) =>
            item.children ? (
              <div
                key={item.label}
                {...getDropdownHandlers(item.label)}
                className={`nav-dropdown${
                  item.dropdownClass ? ` ${item.dropdownClass}` : ""
                }${openDropdown === item.label ? " open" : ""}${
                  childIsActive(item.children, activeHash) ? " active" : ""
                }`}
              >
                <button
                  type="button"
                  className="nav-link nav-link--dropdown"
                  aria-expanded={openDropdown === item.label}
                  aria-haspopup="true"
                  onClick={() => {
                    if (!isDesktopNav) toggleMobileDropdown(item.label);
                  }}
                >
                  {item.label}
                  <span className="nav-caret" aria-hidden="true" />
                </button>

                <div className="nav-mega">
                  <div className="nav-mega-grid">
                    {item.children.map((child) => (
                      <a
                        key={child.label}
                        href={child.href}
                        className={`nav-mega-link${
                          isActive(child.href, activeHash) ? " active" : ""
                        }`}
                        onClick={closeMobile}
                      >
                        {child.label}
                      </a>
                    ))}
                  </div>
                </div>
              </div>
            ) : (
              <a
                key={item.label}
                href={item.href}
                className={`nav-link${
                  isActive(item.href, activeHash) ? " active" : ""
                }`}
                onClick={closeMobile}
              >
                {item.label}
              </a>
            )
          )}
        </nav>

        <a href="#contact" className="btn btn-primary btn-sm nav-cta">
          Get a Quote
        </a>

        <button
          className="nav-toggle"
          aria-label="Toggle menu"
          aria-expanded={open}
          onClick={() => setOpen((v) => !v)}
        >
          <span></span>
          <span></span>
          <span></span>
        </button>
      </div>
    </header>
  );
}
